version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  app:
    build: .
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'
    links:
      - postgres
    depends_on:
      - postgres
    command: >
      gunicorn -b 0.0.0.0:5000
      --access-logfile -
      --reload
      'app:create_app()'

volumes:
  postgres: