version: '2'

services:
  app:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5000
      --access-logfile -
      --reload
      'app:create_app()'
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'